#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

# Make the root directory for repos
mkdir -p "$PLUSHU_ROOT/repos"
if [[ "$EUID" == 0 ]]; then
  chown -R "$PLUSHU_USER" "$PLUSHU_ROOT/repos"
fi
