#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ -n "$PLUSHU_REPO_NAME" ]]; then
  repo=$PLUSHU_REPO_NAME
fi

if [[ -n "$2" ]]; then
  repo=$2
  shift
fi

if [[ -z "$repo" ]]; then
  echo "Missing repo name" >&2
  exit 1
fi

# Call out to integration plugins to delete the repo(s)
"$PLUSHU_ROOT/lib/plushook" delete-repo $repo
